services:
  resume-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: resume-api:0.1
    volumes:
      - resume-data:/app/data
    env_file:
      - ./.env
    environment:
      PORT: "8080"
    ports:
      - "8000:8080"

volumes:
  resume-data:
