"""add document table

Revision ID: f74c464133e8
Revises: ba246ab63508
Create Date: 2026-08-21 13:11:13.860781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74c464133e8'
down_revision: Union[str, Sequence[str], None] = 'ba246ab63508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('revision_note', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'revision_id')
    )
    # ### end Alembic commands ###

    # `documents` is append-only, enforced in the database so a revision cannot
    # be rewritten by anything holding the connection. There is no portable way
    # to say that: SQLite raises from a statement trigger, Postgres needs a
    # trigger function. The SQLite branch is byte-for-byte what this migration
    # always emitted, so databases that already ran it are unaffected.
    if op.get_bind().dialect.name == "postgresql":
        # A function per operation, each with a fixed message: plpgsql reads a
        # lone `%` in a RAISE as a placeholder, so one message built from TG_OP
        # would need an escape that also survives the DBAPI's paramstyle.
        op.execute("""
            CREATE OR REPLACE FUNCTION documents_no_update()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'Updates are forbidden on append-only table: documents';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE OR REPLACE FUNCTION documents_no_delete()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'Deletions are forbidden on append-only table: documents';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER ts_documents_no_update
            BEFORE UPDATE ON documents
            FOR EACH ROW EXECUTE FUNCTION documents_no_update();
        """)
        op.execute("""
            CREATE TRIGGER ts_documents_no_delete
            BEFORE DELETE ON documents
            FOR EACH ROW EXECUTE FUNCTION documents_no_delete();
        """)
    else:
        op.execute("""
               CREATE TRIGGER IF NOT EXISTS ts_documents_no_update
               BEFORE UPDATE ON documents
               BEGIN
                   SELECT RAISE(FAIL, 'Updates are forbidden on append-only table: documents');
               END;
           """)
        # Prevent Deletes
        op.execute("""
               CREATE TRIGGER IF NOT EXISTS ts_documents_no_delete
               BEFORE DELETE ON documents
               BEGIN
                   SELECT RAISE(FAIL, 'Deletions are forbidden on append-only table: documents');
               END;
           """)


def downgrade() -> None:
    """Downgrade schema."""
    # Was `op.drop_table('doc_data')` — a table this migration never created,
    # so the downgrade always failed. Dropping the table takes its triggers
    # with it on both dialects; the Postgres function is a separate object and
    # has to go explicitly.
    op.drop_table('documents')
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS documents_no_update()")
        op.execute("DROP FUNCTION IF EXISTS documents_no_delete()")
